[target.aarch64-apple-ios]
rustflags = [
    "-C", "link-arg=-target",
    "-C", "link-arg=aarch64-apple-ios13.0",
    "-C", "link-arg=-Wl,-application_extension"
]

[target.aarch64-apple-ios-sim]
rustflags = [
    "-C", "link-arg=-target", 
    "-C", "link-arg=aarch64-apple-ios13.0-simulator",
    "-C", "link-arg=-Wl,-application_extension"
]

[target.x86_64-apple-ios]
rustflags = [
    "-C", "link-arg=-target",
    "-C", "link-arg=x86_64-apple-ios13.0-simulator", 
    "-C", "link-arg=-Wl,-application_extension"
]
